// <auto-generated />
using InventoryManeger.DataBase;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InventoryManeger.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250109090445_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("InventoryManeger.Entity.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BorrowedById")
                        .HasColumnType("int");

                    b.Property<bool>("IsAvailabel")
                        .HasColumnType("bit");

                    b.Property<string>("Naem")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("quentity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BorrowedById");

                    b.ToTable("Products", (string)null);
                });

            modelBuilder.Entity("InventoryManeger.Entity.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Passwrod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("InventoryManeger.Entity.Product", b =>
                {
                    b.HasOne("InventoryManeger.Entity.User", "BorrowedBy")
                        .WithMany("BorrowedProduct")
                        .HasForeignKey("BorrowedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BorrowedBy");
                });

            modelBuilder.Entity("InventoryManeger.Entity.User", b =>
                {
                    b.Navigation("BorrowedProduct");
                });
#pragma warning restore 612, 618
        }
    }
}
